//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _NEOPIXEL_H_
#define _NEOPIXEL_H_

#include <TinyCLR_Interop.h>
struct Library_NeoPixel_NeoPixel_NeoPixelNative
{
    TINYCLR_NATIVE_DECLARE(Write___STATIC__VOID__SZARRAY_U1__I4__U4);

    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_NeoPixelNative;

#endif  //_NEOPIXEL_H_
