//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "NeoPixel.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    Library_NeoPixel_NeoPixel_NeoPixelNative::Write___STATIC__VOID__SZARRAY_U1__I4__U4,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_NeoPixelNative =
{
    "NeoPixelNative", 
    0x87B008F1,
    method_lookup
};

